{
  "variables": {
    "ansible_host": "default"
  },
  "builders":
  [{
    "type": "docker",
    "image": "ubuntu:14.04",
    "commit": "true",
    "run_command": [
      "-d",
      "-i",
      "-t",
      "--name",
      "{{user `ansible_host`}}",
      "{{.Image}}",
      "/bin/bash"
    ]
  }],
  "provisioners":
  [{
    "type": "shell",
    "scripts": [
      "../scripts/ansible_install.sh"
    ]
  },
  {
    "type": "ansible-local",
    "playbook_file": "../ansible/docker-playbook.yml",
    "role_paths": [
      "../ansible/roles/common",
      "../ansible/roles/aws"
    ]
  }],
  "post-processors":
  [{
    "type": "docker-tag",
    "repository": "050532389887.dkr.ecr.us-west-2.amazonaws.com/chidevops",
    "tag": "0.1"
  },
  {
    "type": "docker-push",
    "ecr_login": true,
    "aws_access_key": "{{ user `aws_access_key` }}",
    "aws_secret_key": "{{ user `aws_secret_key` }}",
    "login_server": "0505-3238-9887.dkr.ecr.us-west-2.amazonaws.com"
  }]
}
