---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    createuser: 'vagrant'
    createpassword: 'vagrant'
  tasks:
    - name: Setup | create user
      command: useradd -m {{ createuser }} creates=/home/{{ createuser }}

    - name: Setup | set user password
      shell: usermod -p $(echo '{{ createpassword }}' | openssl passwd -1 -stdin) {{ createuser }}

    - name: Setup | authorized key upload
      authorized_key: user={{ createuser }}
        key="{{ lookup('file', 'id_rsa.pub') }}"
        path='/home/{{ createuser }}/.ssh/authorized_keys'
        manage_dir=no

    - name: Sudoers | update sudoers file and validate
      lineinfile: "dest=/etc/sudoers
        insertafter=EOF
        line='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
        regexp='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
        state=present"

  roles:
    - common
    - aws
