_common_dependencies:
    - build-essential
    - curl
    - gcc
    - zlib1g-dev
    - libffi-dev
    - libssl-dev
    - ansible
    - python
    - python-dev
    - apt-transport-https
    - ca-certificates
    - git
    - wget
    - curl
    - vim
    - zsh
    - htop
    - ntp

_guest_utils:
  - virtualbox-guest-utils
