---
- name: Install aws cli
  tags: 'aws-cli'
  become: yes
  pip: name=awscli state=latest

- name: Create the AWS config directory
  tags: 'aws-cli'
  become: yes
  file:
    path={{ home_dir }}/.aws
    state=directory
    owner={{ aws_cli_user }}
    group={{ aws_cli_group }}
    mode=0755

- name: 'Copy AWS CLI config'
  tags: 'aws-cli'
  become: 'yes'
  template: >
    src=aws_cli_config.j2
    dest={{ home_dir }}/.aws/config
    owner={{ aws_cli_user }}
    group={{ aws_cli_group }}
    mode=0600
