---
- name: Ensure we got docker apt repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

- name: Ensure we got docker gpg key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Ensure apt cache is updated.
  apt: update_cache=yes

- name: Has docker
  apt: name=docker-engine force=yes state=present

- name: Add vagrant to docker group
  user: name=vagrant groups=docker append=yes
